 * Serving Flask app 'web'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
127.0.0.1 - - [08/Feb/2023 18:02:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:02:20] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:02:39] "GET /redir HTTP/1.1" 302 -
127.0.0.1 - - [08/Feb/2023 18:02:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:02:39] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [08/Feb/2023 18:03:05] "POST /command HTTP/1.1" 302 -
127.0.0.1 - - [08/Feb/2023 18:03:05] "GET /ac HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:03:05] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [08/Feb/2023 18:03:18] "POST /ac/add HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\GIT\Soundbot\web.py", line 135, in acadd
    volume = post[3][1]
IndexError: list index out of range
127.0.0.1 - - [08/Feb/2023 18:03:18] "GET /ac/add?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:03:18] "GET /ac/add?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:03:18] "GET /ac/add?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:03:18] "GET /ac/add?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'C:\\GIT\\Soundbot\\templates\\emptycog.py', reloading
AC
ImmutableMultiDict([('command', 'potat'), ('response', 'yee'), ('file', '')])
('command', 'potat'), ('response', 'yee'), ('file', '')
[['command', 'potat'], ['response', 'yee'], ['file', '']]
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
 * Detected change in 'C:\\GIT\\Soundbot\\templates\\emptycog.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
 * Detected change in 'C:\\GIT\\Soundbot\\templates\\emptycog.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
 * Detected change in 'C:\\GIT\\Soundbot\\commandwrapper.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
 * Detected change in 'C:\\GIT\\Soundbot\\commandwrapper.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
 * Detected change in 'C:\\GIT\\Soundbot\\commandwrapper.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
127.0.0.1 - - [08/Feb/2023 18:29:14] "POST /ac/delete HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\GIT\Soundbot\web.py", line 165, in acdelete
    commandwrapper(False, command, "", "")
TypeError: commandwrapper() missing 1 required positional argument: 'volume'
127.0.0.1 - - [08/Feb/2023 18:29:14] "GET /ac/delete?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:29:14] "GET /ac/delete?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:29:14] "GET /ac/delete?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:29:14] "GET /ac/delete?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'C:\\GIT\\Soundbot\\web.py', reloading
ImmutableMultiDict([('command', 'bjork')])
('command', 'bjork')
[['command', 'bjork']]
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
Traceback (most recent call last):
  File "C:\GIT\Soundbot\commandwrapper.py", line 91, in <module>
    if add == True:
NameError: name 'add' is not defined
127.0.0.1 - - [08/Feb/2023 18:29:48] "POST /ac/delete HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Shadow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'acdelete' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [08/Feb/2023 18:29:48] "GET /ac/delete?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [08/Feb/2023 18:29:48] "GET /ac/delete?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [08/Feb/2023 18:29:48] "GET /ac/delete?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [08/Feb/2023 18:30:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Feb/2023 18:30:03] "GET /static/style.css HTTP/1.1" 304 -
 * Detected change in 'C:\\GIT\\Soundbot\\web.py', reloading
ImmutableMultiDict([('command', 'bjork')])
('command', 'bjork')
[['command', 'bjork']]
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 892-183-792
